services:
  - type: web
    name: yt-playlist-length
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:fapp --host 0.0.0.0 --port $PORT
    envVars:
      - key: APIS
        sync: false # This will be manually set in dashboard
      - key: PYTHON_VERSION
        value: 3.11 